### ISSUE TITLE
No rpi-config-ap on network list

### ISSUE THREAD

**Issue by asangadev** [sabhiram/raspberry-wifi-conf#11]
Hi, Thanks lot for the great wifi conf. I have followed all the steps/instructions and installed the raspberry-wifi-conf on my Raspberry pi 2 Model 2 (with Raspbian Jessie fresh copy). But I can't see the rpi-config-ap on my wifi network list. I'm using EDUP wifi dongle (EP-N8553). I have attached an screenshot. This is what I'm getting on the terminal. Could you please help me guys?

![terminal](https://cloud.githubusercontent.com/assets/16328655/11857750/5890f45a-a4af-11e5-98e9-5f15692e7111.jpg)

**Comment by asangadev** [comment]
Okay, I fixed it. 

Step 01: install hostapd.
sudo apt-get install bridge-utils hostapd

Step 02: Change wifi_driver_type to rtl871xdrv. 
file path : raspberry-wifi-conf/config.json

{
    "wifi_interface": "wlan0",
    "wifi_driver_type": "rtl871xdrv",

    "access_point": {
        "force_reconfigure": true,
        "wifi_interface":    "wlan0",
        "ssid":              "rpi-config-ap",
        "passphrase":        "zzzzzzzz",
        "domain":            "rpi.config",
        "ip_addr":           "192.168.44.1",
        "netmask":           "255.255.255.0",
        "subnet_ip":         "192.168.44.0",
        "broadcast_address": "192.168.44.255",
        "subnet_range": {
            "start":         "192.168.44.10",
            "end":           "192.168.44.50"
        }
    },

    "server": {
        "port": 88
    }
}


Step 03:
$cd raspberry-wifi-conf
$sudo mv /usr/sbin/hostapd /usr/sbin/hostapd.OLD
$sudo mv assets/bin/hostapd.rtl871xdrv /usr/sbin/hostapd
$sudo chmod 755 /usr/sbin/hostapd

**Comment by sabhiram** [comment]
Yea I was sort of aware and afraid of this - I tried to document some of it in the gotchas section of the readme. I doubt I did a good enough job :(

Thank you for your findings, I will try and update the readme one of these days when I find some time.

**Comment by asangadev** [comment]
No worries mate. Your code really helped me. Thanks again!
