### ISSUE TITLE
After Password entered it binds immediately 

### ISSUE THREAD

**Issue by wazhere2600** [sabhiram/raspberry-wifi-conf#13]
After submitting the password for my AP, it appears to be locked up but in fact it binds and activates on network without a reset.

Is there a way to make this tell the user to reset and not make changes active until reset?

Thanks

**Comment by sabhiram** [comment]
When you say reset, do you mean the web-ui being refreshed? Or are you talking about the RaspberryPi resetting?

**Comment by wazhere2600** [comment]
The pi does not reset, as far as I can tell. The GUI appears to freeze but in fact it takes the value of the new access point and the gui no longer responds. It doesn't say to reset pi just hangs. If I check it in fact already switches over to use the access point that the password was entered for. I really want to try to have it tell the user it's ip and have them reset the pi manually. Any ideas? Thanks for the response

**Comment by sabhiram** [comment]
Oh I see what you are saying. What it does today is I think reset the Pi which should put it in the expected Wifi network. It would be very useful for it to somehow tell the browser its IP but short of having a dual USB wifi dongle solution, I dont see how you can get the IP and send it to the connection to the browser over the old IP.
