### ISSUE TITLE
PI starts in AP mode after entering the wifi credentials

### ISSUE THREAD

**Issue by Snyder1977** [sabhiram/raspberry-wifi-conf#15]
@marko8904

I have installed marko8904's fork. It is possible to enter the wifi credentials and my pi connects successfully to my wifi network at home:

pi@raspberrypi:~/raspberry-wifi-conf $ sudo npm start

> raspberry-wifi-conf@0.0.1 start /home/pi/raspberry-wifi-conf
> node server.js

Wifi is not enabled, Enabling AP for self-configure

Force reconfigure enabled - reset AP
ifdown wlan0 successful...
ifup wlan0 successful...
... dhcp server restarted!
... hostapd restarted!
... AP Enable Success!
Server got /rescan_wifi
Found new interface: wlan0
... dhcp server stopped!
ifdown wlan0 successful...
ifup wlan0 successful...
Wifi Enabled! - Exiting

pi@raspberrypi:~/raspberry-wifi-conf $ ifconfig wlan0
wlan0     Link encap:Ethernet  HWaddr b8:27:eb:6c:ec:ac  
          *_inet addr:192.168.178.35 *_ Bcast:192.168.178.255  Mask:255.255.255.0
          inet6 addr: fe80::a473:5731:9a51:f2dd/64 Scope:Link
          inet6 addr: fe80::9f22:eef2:ccc7:a6fb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:475 errors:0 dropped:8 overruns:0 frame:0
          TX packets:652 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:82719 (80.7 KiB)  TX bytes:298114 (291.1 KiB)

After rebooting my pi starts in the AP mode again and does not connect to the wifi network:

pi@raspberrypi:~ $ ifconfig wlan0
wlan0     Link encap:Ethernet  HWaddr b8:27:eb:6c:ec:ac  
         *\* inet addr:192.168.44.1*\*  Bcast:192.168.44.255  Mask:255.255.255.0
          inet6 addr: fe80::9f22:eef2:ccc7:a6fb/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:46 errors:0 dropped:5 overruns:0 frame:0
          TX packets:86 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:8588 (8.3 KiB)  TX bytes:16187 (15.8 KiB)

Why does the pi start in AP mode again and why does it not connect to my wifi network although I have entered the credentials via smartphone?

Many thanks in advance for any help. I would really like to get this working :-)

**Comment by sabhiram** [comment]
Sorry, but any idea what @marko8904's fork changes?

I have not looked into this for a while - give me some time to see what might be up.

**Comment by Snyder1977** [comment]
I do not know what the difference between your repository and @marko8904's fork is. I am not very good at programming java. I got mark8904's running. Adding some time sleep in /etc/rc.local  before executing 
'cd /home/pi/raspberry-wifi-conf
sudo /usr/bin/node server.js' 
helped.

**Comment by jchirik** [comment]
hey @Snyder1977 - any tips on how you got this running on your rpi3? I'm having the same issue. 

I can get past AP mode fine, and my wpa_supplicant is updated with the SSID & PSK that I inputted from my phone's web browser. But afterwards, my rpi3 doesn't connect to any wifi, even upon reboot.

**Comment by gregoryz7** [comment]
Same issue here. Any solutions found?

**Comment by sabhiram** [comment]
In the config.js file - if the `force_reconfigure` is set to true - it will always reconfigure the node. With rpi3s - you will need to pull the latest code and follow the readme file to make one small edit to handle `dhcpcd`.
