### ISSUE TITLE
Crash when start

### ISSUE THREAD

**Issue by philipheinser** [sabhiram/raspberry-wifi-conf#18]
```
node server.js

/home/pi/raspberry-wifi-conf/app/wifi_manager.js:136
            info["hw_addr"].toLowerCase() == info["ap_addr"].toLowerCase() &&
                                                             ^
TypeError: Cannot call method 'toLowerCase' of undefined
    at _is_ap_enabled_sync (/home/pi/raspberry-wifi-conf/app/wifi_manager.js:136:62)
    at _is_wifi_enabled_sync (/home/pi/raspberry-wifi-conf/app/wifi_manager.js:115:28)
    at /home/pi/raspberry-wifi-conf/app/wifi_manager.js:126:35
    at /home/pi/raspberry-wifi-conf/app/wifi_manager.js:90:20
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:251:17
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:154:25
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:248:21
    at /home/pi/raspberry-wifi-conf/node_modules/async/lib/async.js:612:34
    at /home/pi/raspberry-wifi-conf/app/wifi_manager.js:76:17
    at ChildProcess.exithandler (child_process.js:645:7)
```

**Comment by sabhiram** [comment]
Oh snap, this was written so long ago! And clearly it is full of holes :)

This possibly means that the parameters being returned from the `iwconfig` command are unexpected.

Here is the line that does the regex match:
https://github.com/sabhiram/raspberry-wifi-conf/blob/master/app/wifi_manager.js#L49

Apologize for not being more useful! But a good start would be to post the output of `iwconfig wlan0` here.

**Comment by adamgoose** [comment]
Sorry, this isn't a copy/paste, so the spacing is off... But it's close...

`iwconfig wlan0`

```
wlan0 .   IEEE 802.11bgn   Mode:Master .  Tx-Power=31 . dBm
              Retry short limit:7 .    RTS .  thr:off .   Frgment thr:off
              Power Management: on
```

**Comment by adamgoose** [comment]
I got it to run the first time I installed.... Steps to reproduce:

1. Fresh install of RASPBIAN JESSIE WITH PIXEL, Version:January 2017, Release date:2017-01-11, Kernel version:4.4
2. `sudo apt-get update && sudo apt-get upgrade`
3. `curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash -`
4. `sudo apt-get install nodejs`
5. `node --version` => v7.5.0
6. `sudo npm install -g bower`
6. git clone this repo && cd
7. `npm install`
8. `bower install`
9. `sudo npm run-script provision`
10. `sudo npm start`

Works fine, except when I hit "submit" in the web UI, the app crashes with the aforementioned exception. Subsequent executions of `sudo npm start` throw the same error on startup.

**Comment by sabhiram** [comment]
Oh odd - seems like the `Access Point` member being missing is causing the exception. Here is what the code expects from `iwconfig`:

```    var ifconfig_fields = {
        "hw_addr":         /HWaddr\s([^\s]+)/,
        "inet_addr":       /inet addr:([^\s]+)/,
    },  iwconfig_fields = {
        "ap_addr":         /Access Point:\s([^\s]+)/,
        "ap_ssid":         /ESSID:\"([^\"]+)\"/,
        "unassociated":    /(unassociated)\s+Nick/,
    },  last_wifi_info = null;```

**Comment by iShift** [comment]
same issue, what i can do?

**Comment by sabhiram** [comment]
I updated some code to prevent this from crashing. I am not sure if it 100% resolves what you are seeing, but its probably worth a shot.

**Comment by sabhiram** [comment]
Closed - not seen in latest commit.
