### ISSUE TITLE
Can see the Network but I can not connect to 192.168.44.1:88

### ISSUE THREAD

**Issue by smallzZz8** [sabhiram/raspberry-wifi-conf#27]
So I am running RPI 3 on the newest raspbian stretch and I can click on the network that the RPI is giving off but I can not connect to the website to to enter my credentials. Now I have no internet and I do not know how to revert.  Does anyone know how to refresh my network files back to normal or know how to fix this issue. Thanks!

**Comment by sabhiram** [comment]
Did you follow the latest instructions with regard to the deny interfaces change?
