### ISSUE TITLE
Can not load Angular from CDN when users phone is connected to Pi AP

### ISSUE THREAD

**Issue by stefangordon** [sabhiram/raspberry-wifi-conf#4]
The users phone/device will not have internet connectivity while connected to the temporary configuration network, so loading angular from the CDN isn't going to work.

<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.11/angular.js"></script>

**Comment by stefangordon** [comment]
Will send a PR for this.

**Comment by sabhiram** [comment]
Oh you are right! I probably had it cached :(

Thanks for catching this! We can just host the assets from the app directly in `app/public/external` or some such folder. 

Thank you @stefangordon

**Comment by sabhiram** [comment]
I am guessing the same issue will occur with font-awesome as well. Once you are done I can add that along unless you beat me to it. Appreciate your help greatly!

**Comment by sabhiram** [comment]
closed by this PR: https://github.com/sabhiram/raspberry-wifi-conf/pull/5
